version: "3"

services:
    attacker1:
        image: handsonsecurity/seed-ubuntu:large
        container_name: seed-attacker1
        tty: true
        cap_add:
                - ALL
        privileged: true
        volumes:
                - ./volumes:/volumes
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.2
     
    attacker2:
        image: handsonsecurity/seed-ubuntu:large
        container_name: seed-attacker2
        tty: true
        cap_add:
                - ALL
        privileged: true
        volumes:
                - ./volumes:/volumes
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.3

    host:
        image: handsonsecurity/seed-ubuntu:large
        container_name: user1
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.6
                  
networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24

